@api = http://localhost:3000

###
GET {{api}}/Reservas


###
POST {{api}}/Reservas
Content-Type: application/json

{
    "nombre": "floria Gómez",
    "telefono": "0303456",
    "email": "raulgomez@example.com",
    "habitacion": "101",
    "fecha_inicio": "2024-10-11",
    "fecha_fin": "2024-10-12"
}

###
GET {{api}}/Habitaciones

### 
POST {{api}}/Habitaciones
Content-Type: application/json

{
    "title": "Prueba",
    "price": 56560,
    "description": "testestes",
    "imageUpload": "https://i.ibb.co/tBvPcX0/105031814.webp"
    
}
